=== GiGatR00n/Aion-Core-v4.7.5/AC-Game/data/static_data/cube_expander/cube_expander.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="../import.xsd"/>
    <xs:element name="cube_expander" type="cubeExpander"/>
    <xs:complexType name="cubeExpander">
        <xs:sequence>
            <xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="cube_npc" type="cubeNpcTemplate" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="cubeNpcTemplate">
        <xs:sequence>
            <xs:element name="expand" type="CubeExpand" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="CubeExpand">
        <xs:attribute name="level" type="xs:int"/>
        <xs:attribute name="price" type="xs:int"/>
    </xs:complexType>
</xs:schema>

=== GiGatR00n/Aion-Core-v4.7.5/AC-Game/data/static_data/cube_expander/cube_expander.xml
<?xml version="1.0" encoding="UTF-8"?>
<cube_expander xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cube_expander.xsd">
    <!-- Poeta -->
    <cube_npc id="798008">
        <expand price="1000" level="1"/>
    </cube_npc>
    <!-- Sanctum -->
    <cube_npc id="798011">
        <expand price="12000" level="2"/>
        <expand price="80000" level="3"/>
        <expand price="180000" level="4"/>
    </cube_npc>
    <cube_npc id="798012">
        <expand price="12000" level="2"/>
        <expand price="80000" level="3"/>
        <expand price="180000" level="4"/>
    </cube_npc>
    <!-- Ishalgen -->
    <cube_npc id="798037">
        <expand price="1000" level="1"/>
    </cube_npc>
    <!-- Pandaemonium -->
    <cube_npc id="798058">
        <expand price="1000" level="1"/>
        <expand price="12000" level="2"/>
        <expand price="80000" level="3"/>
        <expand price="180000" level="4"/>
    </cube_npc>
    <cube_npc id="798059">
        <expand price="1000" level="1"/>
        <expand price="12000" level="2"/>
        <expand price="80000" level="3"/>
        <expand price="180000" level="4"/>
    </cube_npc>
    <!-- Abyss, Tigraki Island -->
    <cube_npc id="279022">
        <expand price="360000" level="5"/>
    </cube_npc>
    <!-- Test Cube Upgrade -->
    <cube_npc id="203218">
        <expand level="1" price="1000"/>
        <expand level="2" price="12000"/>
        <expand level="3" price="80000"/>
    </cube_npc>
    <!-- Test Cube Upgrade -->
    <cube_npc id="203219">
        <expand level="2" price="12000"/>
        <expand level="4" price="180000"/>
    </cube_npc>
</cube_expander>
